name: food_diary
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  get_it: ^7.2.0
  intl: ^0.17.0
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  sqflite: ^2.0.1

dev_dependencies:
  bloc_test: ^9.0.2
  faker: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  sqflite_common_ffi: ^2.1.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: "AppLocalization"
